"""
Diffusion World Model Maze Game
================================
A 2D maze game where the world is maintained and generated by a small
diffusion model. The model takes a fixed-size window of past frames +
the player's action and denoises the next game state.

Architecture:
  - Maze: generated once with recursive backtracker, encoded as pixel grid
  - World Model: tiny U-Net that denoises next_frame given context_window + action
  - Context window: last N rendered frames stored as tensors
  - At each step: model predicts next frame via DDPM-style denoising
  - Player position is injected into the predicted frame (so physics stay crisp)
"""

import sys
import math
import random
import collections
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pygame

# ─────────────────────────── constants ────────────────────────────────────────
CELL = 16  # pixels per maze cell
COLS = 19  # maze grid columns (odd for walls)
ROWS = 19  # maze grid rows
W = COLS * CELL  # window width
H = ROWS * CELL  # window height
FPS = 30

CONTEXT_LEN = 4  # how many past frames the model sees
DIFF_STEPS = 6  # DDPM denoising steps at inference (fast)
TRAIN_STEPS = 200  # how many steps to warm-up-train before play

# Colours (RGB)
C_WALL = (30, 30, 50)
C_FLOOR = (200, 195, 175)
C_PLAYER = (80, 160, 240)
C_GOAL = (240, 180, 60)
C_FOG = (15, 15, 25)

# ─────────────────────────── Maze generation ──────────────────────────────────


def generate_maze(cols, rows):
    """Recursive backtracker. Returns 2-D bool grid: True = wall."""
    grid = [[True] * cols for _ in range(rows)]

    def carve(r, c):
        grid[r][c] = False
        dirs = [(0, 2), (0, -2), (2, 0), (-2, 0)]
        random.shuffle(dirs)
        for dr, dc in dirs:
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc]:
                grid[r + dr // 2][c + dc // 2] = False
                carve(nr, nc)

    carve(1, 1)
    # ensure border walls
    for i in range(rows):
        grid[i][0] = grid[i][-1] = True
    for j in range(cols):
        grid[0][j] = grid[-1][j] = True
    return grid


def maze_to_surface(maze, player_pos, goal_pos, fog=None):
    """Render maze + player + goal onto a pygame Surface (W×H)."""
    surf = pygame.Surface((W, H))
    for r in range(ROWS):
        for c in range(COLS):
            rect = pygame.Rect(c * CELL, r * CELL, CELL, CELL)
            if fog and fog[r][c]:
                surf.fill(C_FOG, rect)
            elif maze[r][c]:
                surf.fill(C_WALL, rect)
            else:
                surf.fill(C_FLOOR, rect)
    # goal
    gr, gc = goal_pos
    pygame.draw.rect(
        surf, C_GOAL, pygame.Rect(gc * CELL + 2, gr * CELL + 2, CELL - 4, CELL - 4)
    )
    # player
    pr, pc = player_pos
    cx, cy = pc * CELL + CELL // 2, pr * CELL + CELL // 2
    pygame.draw.circle(surf, C_PLAYER, (cx, cy), CELL // 2 - 1)
    return surf


def surface_to_tensor(surf):
    """pygame Surface → float32 tensor [3, H, W] in [0,1]."""
    arr = pygame.surfarray.array3d(surf)  # (W, H, 3)
    arr = arr.transpose(2, 1, 0)  # (3, H, W)
    return torch.tensor(arr, dtype=torch.float32) / 255.0


def tensor_to_surface(t):
    """float32 tensor [3, H, W] → pygame Surface."""
    arr = (t.clamp(0, 1) * 255).byte().cpu().numpy()
    arr = arr.transpose(1, 2, 0)  # (H, W, 3)
    arr = arr.transpose(1, 0, 2)  # (W, H, 3)  pygame wants this
    surf = pygame.Surface((W, H))
    pygame.surfarray.blit_array(surf, arr)
    return surf


# ─────────────────────────── Tiny U-Net diffusion model ───────────────────────


class GroupNorm4D(nn.Module):
    """GroupNorm that decomposes to WebGL-compatible 4-D ONNX ops.

    Standard GroupNorm exported to ONNX (opset < 21) uses a 3-D Reshape
    [N, C, H, W] → [N, G, C//G*H*W] before InstanceNormalization, which
    the onnxruntime-web WebGL backend rejects (only supports 4-D).

    This implementation reshapes to [N, G, C//G, H*W] (always 4-D) and
    normalizes with explicit ReduceMean/Var — no InstanceNorm in the graph."""

    def __init__(self, num_groups, num_channels, eps=1e-5):
        super().__init__()
        self.num_groups = num_groups
        self.num_channels = num_channels
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(num_channels))
        self.bias = nn.Parameter(torch.zeros(num_channels))

    def forward(self, x):
        N, C, H, W = x.shape
        G = self.num_groups
        # [N, C, H, W] → [N, G, C//G, H*W]   stays 4-D (WebGL-safe)
        x = x.reshape(N, G, C // G, -1)
        mean = x.mean(dim=[2, 3], keepdim=True)
        var = x.var(dim=[2, 3], keepdim=True, unbiased=False)
        x = (x - mean) / torch.sqrt(var + self.eps)
        # [N, G, C//G, H*W] → [N, C, H, W]
        x = x.reshape(N, C, H, W)
        return x * self.weight.view(1, C, 1, 1) + self.bias.view(1, C, 1, 1)

class ResBlock(nn.Module):
    def __init__(self, ch):
        super().__init__()
        self.net = nn.Sequential(
            GroupNorm4D(min(8, ch), ch),
            nn.SiLU(),
            nn.Conv2d(ch, ch, 3, padding=1),
            GroupNorm4D(min(8, ch), ch),
            nn.SiLU(),
            nn.Conv2d(ch, ch, 3, padding=1),
        )

    def forward(self, x):
        return x + self.net(x)


class DiffusionWorldModel(nn.Module):
    """
    Input:  context (CONTEXT_LEN × 3 channels) + noisy frame (3 ch) + action (4 ch one-hot) + timestep emb
    Output: denoised frame (3 ch)

    Tiny U-Net: enc → bottleneck → dec, skip connections.
    """

    def __init__(self, context_len=CONTEXT_LEN, base_ch=32):
        super().__init__()
        in_ch = (
            context_len * 3 + 3 + 4 + 1
        )  # context + noisy + action + t_emb broadcast

        # encoder
        self.enc1 = nn.Sequential(
            nn.Conv2d(in_ch, base_ch, 3, padding=1), ResBlock(base_ch)
        )
        self.enc2 = nn.Sequential(
            nn.Conv2d(base_ch, base_ch * 2, 3, stride=2, padding=1),
            ResBlock(base_ch * 2),
        )
        self.enc3 = nn.Sequential(
            nn.Conv2d(base_ch * 2, base_ch * 4, 3, stride=2, padding=1),
            ResBlock(base_ch * 4),
        )

        # bottleneck
        self.bot = nn.Sequential(ResBlock(base_ch * 4), ResBlock(base_ch * 4))

        # decoder
        self.dec3 = nn.Sequential(
            nn.ConvTranspose2d(base_ch * 4, base_ch * 2, 4, stride=2, padding=1),
            ResBlock(base_ch * 2),
        )
        self.dec2 = nn.Sequential(
            nn.ConvTranspose2d(base_ch * 4, base_ch, 4, stride=2, padding=1),
            ResBlock(base_ch),
        )
        self.out = nn.Conv2d(base_ch * 2, 3, 1)

    def forward(self, context, noisy, action, t_frac):
        """
        context : (B, CL*3, H, W)
        noisy   : (B, 3, H, W)
        action  : (B, 4)   one-hot
        t_frac  : (B,)     in [0,1]
        """
        B, _, H, W = noisy.shape
        # broadcast action + t as extra channels
        act_ch = action.view(B, 4, 1, 1).expand(B, 4, H, W)
        t_ch = t_frac.view(B, 1, 1, 1).expand(B, 1, H, W)
        x = torch.cat([context, noisy, act_ch, t_ch], dim=1)

        e1 = self.enc1(x)  # (B, ch,   H,   W)
        e2 = self.enc2(e1)  # (B, ch*2, H/2, W/2)
        e3 = self.enc3(e2)  # (B, ch*4, H/4, W/4)
        b = self.bot(e3)
        d3 = self.dec3(b)  # (B, ch*2, H/2, W/2)
        d2 = self.dec2(torch.cat([d3, e2], dim=1))  # (B, ch,   H,   W)
        out = self.out(torch.cat([d2, e1], dim=1))  # (B, 3,   H,   W)
        return out


# ─────────────────────────── DDPM noise schedule ──────────────────────────────


def cosine_betas(T=1000):
    s = 0.008
    steps = torch.arange(T + 1, dtype=torch.float32)
    alphas_bar = torch.cos((steps / T + s) / (1 + s) * math.pi / 2) ** 2
    alphas_bar = alphas_bar / alphas_bar[0]
    betas = 1 - alphas_bar[1:] / alphas_bar[:-1]
    return betas.clamp(0, 0.999)


T_TOTAL = 1000
betas = cosine_betas(T_TOTAL)
alphas = 1.0 - betas
alphas_cumprod = torch.cumprod(alphas, 0)


def q_sample(x0, t_idx):
    """Add noise to x0 at timestep t_idx (int tensor B)."""
    a = alphas_cumprod[t_idx].view(-1, 1, 1, 1).to(x0.device)
    noise = torch.randn_like(x0)
    return a.sqrt() * x0 + (1 - a).sqrt() * noise, noise


def p_sample_step(model, x_t, context, action, t_idx, t_next_idx):
    """One DDPM denoising step."""
    B = x_t.shape[0]
    device = x_t.device
    t_frac = (t_idx / T_TOTAL).float().to(device).expand(B)

    with torch.no_grad():
        pred_noise = model(context, x_t, action, t_frac)

    at = alphas_cumprod[t_idx].to(device)
    at1 = (
        alphas_cumprod[t_next_idx].to(device) if t_next_idx >= 0 else torch.tensor(1.0)
    )

    # predict x0
    x0_pred = (x_t - (1 - at).sqrt() * pred_noise) / at.sqrt()
    x0_pred = x0_pred.clamp(-1, 1)

    if t_next_idx < 0:
        return x0_pred

    # compute x_{t-1}
    coef1 = at1.sqrt() * (1 - at / at1) / (1 - at)
    coef2 = (at / at1).sqrt() * (1 - at1) / (1 - at)
    mean = coef1 * x0_pred + coef2 * x_t
    var = betas[t_idx].to(device) * (1 - at1) / (1 - at)
    return mean + var.sqrt() * torch.randn_like(x_t)


def ddpm_infer(model, context, action, steps=DIFF_STEPS, device="cpu"):
    """Fast DDPM sampling with `steps` denoising steps."""
    B = context.shape[0]
    x = torch.randn(B, 3, H, W, device=device)
    t_seq = torch.linspace(T_TOTAL - 1, 0, steps).long()
    for i, t in enumerate(t_seq):
        t_next = t_seq[i + 1] if i + 1 < len(t_seq) else -1
        t_b = t.expand(B)
        x = p_sample_step(
            model, x, context, action, t_b, t_next if t_next == -1 else t_next.expand(B)
        )
    return x


# ─────────────────────────── Training loop helper ─────────────────────────────


def train_on_replay(model, optimizer, replay, device, steps=50):
    """Train model on stored (context, frame, action) tuples."""
    if len(replay) < 4:
        return 0.0
    model.train()
    total_loss = 0.0
    for _ in range(steps):
        batch = random.choices(replay, k=4)
        ctx_b = torch.stack([b[0] for b in batch]).to(device)
        frame_b = torch.stack([b[1] for b in batch]).to(device)
        act_b = torch.stack([b[2] for b in batch]).to(device)

        t_idx = torch.randint(0, T_TOTAL, (4,))
        noisy, noise = q_sample(frame_b * 2 - 1, t_idx)  # scale to [-1,1]
        t_frac = (t_idx.float() / T_TOTAL).to(device)

        pred = model(ctx_b, noisy.to(device), act_b.to(device), t_frac)
        loss = F.mse_loss(pred, noise.to(device))
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item()
    model.eval()
    return total_loss / steps


# ─────────────────────────── Main game ────────────────────────────────────────


def main():
    pygame.init()
    screen = pygame.display.set_mode((W, H * 2 + 20))  # real + predicted stacked
    pygame.display.set_caption("Diffusion World Model Maze")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("monospace", 13)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # ── maze setup ──────────────────────────────────────────────────────────
    maze = generate_maze(COLS, ROWS)
    start_pos = (1, 1)
    goal_pos = (ROWS - 2, COLS - 2)
    player = list(start_pos)
    wins = 0

    # ── model setup ─────────────────────────────────────────────────────────
    model = DiffusionWorldModel(CONTEXT_LEN).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)
    model.eval()

    # action encoding: 0=up 1=down 2=left 3=right  (one-hot, float)
    ACTION_MAP = {pygame.K_UP: 0, pygame.K_DOWN: 1, pygame.K_LEFT: 2, pygame.K_RIGHT: 3}
    DIR_MAP = {0: (-1, 0), 1: (1, 0), 2: (0, -1), 3: (0, 1)}

    def encode_action(a_idx):
        v = torch.zeros(4)
        v[a_idx] = 1.0
        return v

    # context window: deque of tensors [3, H, W]
    ctx_window = collections.deque(maxlen=CONTEXT_LEN)

    def get_context_tensor():
        frames = list(ctx_window)
        while len(frames) < CONTEXT_LEN:
            frames.insert(0, torch.zeros(3, H, W))
        return torch.cat(frames, dim=0).unsqueeze(0).to(device)  # (1, CL*3, H, W)

    # replay buffer
    replay = collections.deque(maxlen=2000)

    def render_real(pos=None):
        p = pos if pos else player
        return maze_to_surface(maze, p, goal_pos)

    # ── initial frames ───────────────────────────────────────────────────────
    for _ in range(CONTEXT_LEN):
        surf = render_real()
        ctx_window.append(surface_to_tensor(surf))

    # ── pre-train by exploring the maze automatically ────────────────────────
    print("Pre-training diffusion model on random maze exploration...")
    pre_player = list(start_pos)
    for step in range(TRAIN_STEPS * 4):
        a_idx = random.randint(0, 3)
        dr, dc = DIR_MAP[a_idx]
        nr, nc = pre_player[0] + dr, pre_player[1] + dc
        if not maze[nr][nc]:
            pre_player = [nr, nc]
        surf = render_real(pre_player)
        frame = surface_to_tensor(surf).cpu()
        ctx_t = get_context_tensor().squeeze(0).detach().cpu()  # (CL*3, H, W)
        act_t = encode_action(a_idx).cpu()
        replay.append((ctx_t, frame, act_t))
        ctx_window.append(frame)
        if step % 200 == 199:
            loss = train_on_replay(model, optimizer, replay, device, steps=80)
            print(f"  step {step + 1}/{TRAIN_STEPS * 4}  loss={loss:.4f}")
    print("Pre-training done. Starting game!\n")

    # reset context to real start
    ctx_window.clear()
    player = list(start_pos)
    for _ in range(CONTEXT_LEN):
        ctx_window.append(surface_to_tensor(render_real()))

    # ── predicted frame placeholder ──────────────────────────────────────────
    pred_surf = render_real()
    last_action = 0
    show_pred = True
    loss_log = 0.0
    step_count = 0

    # ── UI labels ────────────────────────────────────────────────────────────
    def draw_label(text, x, y, col=(200, 200, 200)):
        lbl = font.render(text, True, col)
        screen.blit(lbl, (x, y))

    running = True
    while running:
        moved = False
        a_idx = last_action

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_p:
                    show_pred = not show_pred
                elif event.key in ACTION_MAP:
                    a_idx = ACTION_MAP[event.key]
                    dr, dc = DIR_MAP[a_idx]
                    nr, nc = player[0] + dr, player[1] + dc
                    if not maze[nr][nc]:
                        # ── generate diffusion prediction before moving ──
                        ctx_t = get_context_tensor()
                        act_t = encode_action(a_idx).unsqueeze(0).to(device)
                        with torch.no_grad():
                            pred_t = ddpm_infer(
                                model, ctx_t, act_t, steps=DIFF_STEPS, device=device
                            )
                            pred_t = pred_t.squeeze(0) * 0.5 + 0.5  # back to [0,1]
                        pred_surf = tensor_to_surface(pred_t)

                        # ── actual move ──────────────────────────────────
                        player = [nr, nc]
                        real_surf = render_real()
                        real_frame = surface_to_tensor(real_surf)

                        # store in replay (always CPU to avoid device mismatch)
                        ctx_cpu = ctx_t.squeeze(0).detach().cpu()
                        frame_cpu = real_frame.detach().cpu()
                        act_cpu = encode_action(a_idx).cpu()
                        replay.append((ctx_cpu, frame_cpu, act_cpu))
                        ctx_window.append(real_frame)
                        last_action = a_idx
                        moved = True
                        step_count += 1

                        # ── online fine-tune every 10 steps ──────────────
                        if step_count % 10 == 0:
                            loss_log = train_on_replay(
                                model, optimizer, replay, device, steps=20
                            )

                        # ── win check ─────────────────────────────────────
                        if player == list(goal_pos):
                            wins += 1
                            player = list(start_pos)
                            ctx_window.clear()
                            for _ in range(CONTEXT_LEN):
                                ctx_window.append(surface_to_tensor(render_real()))

        # ── draw ─────────────────────────────────────────────────────────────
        screen.fill((10, 10, 20))

        # top: real game
        real_surf_now = render_real()
        screen.blit(real_surf_now, (0, 0))

        # divider
        pygame.draw.line(screen, (80, 80, 120), (0, H + 8), (W, H + 8), 2)

        # bottom: diffusion prediction
        if show_pred:
            screen.blit(pred_surf, (0, H + 18))
        else:
            screen.fill((20, 20, 35), pygame.Rect(0, H + 18, W, H))

        # labels
        draw_label("REAL  (arrow keys to move)", 4, 2, (180, 220, 255))
        draw_label(
            f"DIFFUSION PREDICTION  [P] toggle   loss={loss_log:.4f}   wins={wins}",
            4,
            H + 10,
            (255, 210, 100),
        )

        # context indicator dots
        filled = sum(1 for _ in ctx_window)
        for i in range(CONTEXT_LEN):
            col = (100, 200, 100) if i < filled else (60, 60, 80)
            pygame.draw.circle(screen, col, (W - 14 - i * 14, 10), 5)

        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
